<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FraudDetection.Worker-2d7e55e0-3ec0-4e58-879e-4050b5938089</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.2.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.18.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.18.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.18.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.18.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.SqlClient" Version="1.18.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FraudDetection.Application\FraudDetection.Application.csproj" />
    <ProjectReference Include="..\FraudDetection.Infrastructure\FraudDetection.Infrastructure.csproj" />
  </ItemGroup>
</Project>
